// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, . . .
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>

using namespace std;

int main()
{
    long int sum = 0;

    long int t1 = 0;
    long int t2 = 1;
    long int t3 = t1 + t2;

    cout << "The require series is : " << t1 << " " << t2 << " ";
    while (t3 <= 4000000)
    {
        t3 = t1 + t2;
        t1 = t2;
        t2 = t3;
        if (t3 % 2 == 0)
        {
            sum += t3;
        }
        cout << t3 << " ";
    }

    cout << endl
         << "The sum of the even number in the series is " << sum << endl;
    return 0;
}